services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sandbox
      MONGO_INITDB_DATABASE: product_service
    volumes:
      - ./docker/mongodb/data:/data/db